import type { Metadata } from "next";
import StyleSheet from "@/styles/style-sheet";
import { AppStyles} from "@/styles/app-styles";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

type Props = {
  children: React.ReactNode;
};

export default function RootLayout({ children }: Props) {
  return (
    <html lang="en">
      <body>
        <StyleSheet>
          <AppStyles />
          <main>
            {children}
          </main>
        </StyleSheet>
      </body>
    </html>
  );
}
